version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
