version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/project_exchange
    depends_on:
      - mongo
    networks:
      - app-network

  node-cron:
    build: ./node-cron
    container_name: node-cron-job
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

  mongo-backup:
    image: mongo:6
    container_name: mongo-backup
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - mongo-backup:/backup
      - .:/project_exchange  # Щоб доступний був файл backup.sh
    depends_on:
      - mongo
    entrypoint: /project_exchange/backup.sh
    networks:
      - app-network
    restart: always

volumes:
  mongo-data:
    driver: local
  mongo-backup:
    driver: local

networks:
  app-network:
    driver: bridge
