version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/project_exchange
    depends_on:
      - mongo
    networks:
      - app-network

  node-cron:
    build: ./node-cron
    container_name: node-cron-job
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"    # HTTP (небезпечно, але потрібно для Let's Encrypt)
      - "443:443"  # HTTPS (захищене з'єднання)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
